Target = crptz
CFLAGS = -g

all: $(Target)

$(Target): main.o crptzip.o
	gcc $(CFLAGS) $^ -o $@

main.o: main.c crptzip.h
	gcc $(CFLAGS) -c main.c

crptzip.o: crptzip.c crptzip.h
	gcc $(CFLAGS) -c crptzip.c

clean:
	rm -f *.o $(Target)
